version: 2.1

jobs:
  build:
    docker: 
      - image: cing/node:14.10.1
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-(( checksum 'package.json'))

      - run:
          comand: npm install
      - save_cache:
          key: v1-dependencies-(( checksum 'package.json'))
          paths:
            - node_modules
      - run:
          command: npm test
        